export const PLANS_RECEIVED = 'PLANS_RECEIVED'
export const PLAN_CREATED = 'PLAN_CREATED'
export const PLAN_PERIODS_RECEIVED = 'PLAN_PERIODS_RECEIVED'
export const PLAN_PERIOD_CREATED = 'PLAN_PERIOD_CREATED'